#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH --mem=16GB
#SBATCH --time=6:00:00
#SBATCH --job-name=mainNN
#SBATCH --partition=gpu
#SBATCH --output=SlurmOutput/main_%j.txt
#SBATCH --account=aero_research_cantwell

module load cuda

source .venv_spectral/bin/activate

python3 nn/main.py --alpha dg --save out1.gif --seed 1
python3 nn/main.py --alpha dg --save out2.gif --seed 6
python3 nn/main.py --alpha dg --save out3.gif --seed 7
python3 nn/main.py --alpha dg --save out4.gif --seed 67