#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=10GB
#SBATCH --time=5:59:00
#SBATCH --job-name=stbS1D
#SBATCH --partition=short
#SBATCH --output=SlurmOutput/Spectral1D.txt
#SBATCH --account=aero_hpc

./build/spectral --P 6 --N 50 --Q 100 --T 0.4 --dt 5e-5 --eps 2. --base1 "RBF::GAUSSIAN"  \
    --sensor "PerssonPeraire" --trunc 3 --s0 -3.0 --kappa 1 --eps0 5e-3 --output HYBRID/SOD_poly_gauss

./build/spectral --P 6 --N 50 --Q 100 --T 0.4 --dt 5e-5 --eps 2. --base1 "RBF::IMQ" \
    --sensor "PerssonPeraire" --trunc 3 --s0 -3.0 --kappa 1 --eps0 5e-3 --output HYBRID/SOD_poly_IMQ
